version: "3.9"

services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: borispetrovich
      POSTGRES_PASSWORD: borispetrovich
      POSTGRES_DB: borispetrovich
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: borispetrovich:latest
    container_name: my-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgresql://db:5432/borispetrovich
      POSTGRES_USER: borispetrovich
      POSTGRES_PASSWORD: borispetrovich
      TG_TOKEN: ${TG_TOKEN}

volumes:
  pgdata: